### ISSUE TITLE
Not working raise ConfigurationError("Empty host " "(or extra comma in host list)

### ISSUE THREAD

**Issue by ScripterSaurav** [WebX-Divin/RenameBot-Premium#1]
2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xappTraceback (most recent call last):

2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xapp File "/webx/bot.py", line 5, in <module>

2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xapp from plugins.cb_data import app as Client2

2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xapp File "/webx/plugins/cb_data.py", line 6, in <module>

2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xapp from helper.database import *

2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xapp File "/webx/helper/database.py", line 6, in <module>

2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xapp mongo = pymongo.MongoClient(DB_URL)

2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xapp File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 703, in __init__

2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xapp seeds.update(uri_parser.split_hosts(entity, port))

2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xapp File "/usr/local/lib/python3.10/site-packages/pymongo/uri_parser.py", line 365, in split_hosts

2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xapp raise ConfigurationError("Empty host " "(or extra comma in host list).")

2023-03-11 11:49:39.78 UTCapp-7b4b5fd45-sph2xapppymongo.errors.ConfigurationError: Empty host (or extra comma in host list).

**Comment by WebX-Divin** [comment]
Check your MongoDB connectiom
